# Generated by Django 4.2.10 on 2024-02-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_fuel_fuelcolumn_fuelcolumnpointer_fuelstorage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
