# Generated by Django 4.2.10 on 2024-03-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_organization_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTypes',
        ),
        migrations.RemoveIndex(
            model_name='fuel',
            name='fuel_day_fb774c_idx',
        ),
        migrations.RenameField(
            model_name='fuelstorage',
            old_name='input_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='fuelcolumn',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='fuelcolumn',
            name='organ',
        ),
        migrations.RemoveField(
            model_name='fuelcolumnpointer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fuelstorage',
            name='output_price',
        ),
        migrations.RemoveField(
            model_name='fuelstorage',
            name='size',
        ),
        migrations.AddField(
            model_name='fuelcolumnpointer',
            name='organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='fuelstorage',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='Tugaganmi'),
        ),
        migrations.AddField(
            model_name='fuelstorage',
            name='remainder',
            field=models.IntegerField(default=2, verbose_name='Kirim Hajmi [litr]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstorage',
            name='residual',
            field=models.IntegerField(default=1, verbose_name='Qoldiq [litr]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['fuel_type'], name='fuel_fuel_ty_6f45b1_idx'),
        ),
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['created_at'], name='fuel_created_44420a_idx'),
        ),
    ]
