# Generated by Django 4.2.10 on 2024-04-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_fuelprice_remove_fuelcolumnpointer_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salefuel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization', verbose_name='Tashkilot'),
        ),
    ]
