# Generated by Django 4.2.10 on 2024-04-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_salefuel_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStorageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('begin', models.IntegerField(verbose_name='Kun boshida [litr]')),
                ('end', models.IntegerField(verbose_name='Kun oxirida [litr]')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fueltype', verbose_name="Yoqilg'i turi")),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "Yoqilg'i ombori tarixi",
                'verbose_name_plural': "Yoqilg'i ombori tarixi",
                'db_table': 'fuel_storage_history',
            },
        ),
    ]
