# Generated by Django 4.2.10 on 2024-04-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_organizationfuelcolumns_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcolumnpointer',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fueltype', verbose_name="Yoqilg'i turi"),
        ),
    ]
