# Generated by Django 5.0.1 on 2024-02-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_fueltype_attr_alter_fueltype_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Kun')),
                ('purchase', models.FloatField(verbose_name='Xarid')),
                ('sale', models.FloatField(verbose_name='Sotish')),
                ('balance', models.FloatField(verbose_name='Qoldiq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fueltype', verbose_name="Yoqilg'i turi")),
            ],
            options={
                'verbose_name': "Yoqilg'i",
                'verbose_name_plural': "Yoqilg'i",
                'db_table': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='FuelColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.organization', verbose_name='Tashkilot')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Xolat')),
            ],
            options={
                'verbose_name': "Yoqilg'i ustuni",
                'verbose_name_plural': "Yoqilg'i ustunlari",
                'db_table': 'fuel_column',
            },
        ),
        migrations.CreateModel(
            name='FuelColumnPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_first', models.FloatField(verbose_name='Hajmi kun boshida [litr]')),
                ('size_last', models.FloatField(verbose_name='Hajmi kun oxirida [litr]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fuel', verbose_name='Kun')),
                ('fuel_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fuelcolumn', verbose_name="Yoqilg'i ustuni")),
            ],
            options={
                'verbose_name': "Yoqilg'i ustuni ko'rsatgichlari",
                'verbose_name_plural': "Yoqilg'i ustuni ko'rsatgichlari",
                'db_table': 'fuel_column_pointer',
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(verbose_name='Hajmi [litr]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fuel', verbose_name='Kun')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fueltype', verbose_name="Yoqilg'i turi")),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.paymenttype', verbose_name="To'lov turi")),
            ],
            options={
                'verbose_name': "Yoqilg'i narxi",
                'verbose_name_plural': "Yoqilg'i narxi",
                'db_table': 'fuel_price',
            },
        ),
        migrations.CreateModel(
            name='FuelStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Hajmi [litr]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fueltype', verbose_name="Yoqilg'i turi")),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "Yoqilg'i ombori",
                'verbose_name_plural': "Yoqilg'i ombori",
                'db_table': 'fuel_storage',
            },
        ),
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['day', 'fuel_type'], name='fuel_day_fb774c_idx'),
        ),
    ]
