# Generated by Django 5.0.1 on 2024-02-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_leader_state_usertypes_user_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='user_roles', to='bot.usertypes', verbose_name='Foydalanuvchi turlari'),
        ),
    ]
