# Generated by Django 5.0.1 on 2024-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_salefuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Qoldiq'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='purchase',
            field=models.FloatField(blank=True, null=True, verbose_name='Xarid'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Sotish'),
        ),
    ]
