# Generated by Django 5.0.1 on 2024-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_fuel_balance_alter_fuel_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salefuel',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='salefuel',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Hajmi [litr]'),
        ),
    ]
