# Generated by Django 4.2.10 on 2024-02-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_channelmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Kun')),
                ('purchase', models.FloatField(blank=True, null=True, verbose_name='Xarid')),
                ('sale', models.FloatField(blank=True, null=True, verbose_name='Sotish')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='Qoldiq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': "Yoqilg'i",
                'verbose_name_plural': "Yoqilg'i",
                'db_table': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='FuelColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': "Yoqilg'i ustuni",
                'verbose_name_plural': "Yoqilg'i ustunlari",
                'db_table': 'fuel_column',
            },
        ),
        migrations.CreateModel(
            name='FuelColumnPointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_first', models.FloatField(blank=True, null=True, verbose_name='Hajmi kun boshida [litr]')),
                ('size_last', models.FloatField(blank=True, null=True, verbose_name='Hajmi kun oxirida [litr]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fuel', verbose_name='Kun')),
                ('fuel_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fuelcolumn', verbose_name="Yoqilg'i ustuni")),
            ],
            options={
                'verbose_name': "Yoqilg'i ustuni ko'rsatgichlari",
                'verbose_name_plural': "Yoqilg'i ustuni ko'rsatgichlari",
                'db_table': 'fuel_column_pointer',
            },
        ),
        migrations.CreateModel(
            name='FuelStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Hajmi [litr]')),
                ('input_price', models.FloatField(verbose_name='Kirim narxi')),
                ('output_price', models.FloatField(verbose_name='Chiqim narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': "Yoqilg'i ombori",
                'verbose_name_plural': "Yoqilg'i ombori",
                'db_table': 'fuel_storage',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': "Yoqilg'i turi",
                'verbose_name_plural': "Yoqilg'i turlari",
                'db_table': 'fuel_type',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('leader', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rahbar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': "To'lov turi",
                'verbose_name_plural': "To'lov turlari",
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='SaleFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(blank=True, null=True, verbose_name='Hajmi [litr]')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fuel', verbose_name='Kun')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fueltype', verbose_name="Yoqilg'i turi")),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.paymenttype', verbose_name="To'lov turi")),
            ],
            options={
                'verbose_name': "Sotilgan yoqilg'i",
                'verbose_name_plural': "Sotilgan yoqilg'i",
                'db_table': 'sale_fuel',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi turi',
                'verbose_name_plural': 'Foydalanuvchi turlari',
                'db_table': 'user_types',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='ChannelMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Reklama',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana"),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ismi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanuvchi nomi'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='fuelstorage',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fueltype', verbose_name="Yoqilg'i turi"),
        ),
        migrations.AddField(
            model_name='fuelstorage',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='fuelcolumn',
            name='organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.fueltype', verbose_name="Yoqilg'i turi"),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddIndex(
            model_name='salefuel',
            index=models.Index(fields=['day', 'fuel_type', 'payment_type'], name='sale_fuel_day_id_ca1d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='fuel',
            index=models.Index(fields=['day', 'fuel_type'], name='fuel_day_fb774c_idx'),
        ),
    ]
