# Generated by Django 4.2.10 on 2024-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_rename_is_lider_user_is_leader'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salefuel',
            name='sale_fuel_day_id_ca1d4d_idx',
        ),
        migrations.RemoveField(
            model_name='salefuel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='salefuel',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='salefuel',
            name='size',
        ),
        migrations.AddField(
            model_name='salefuel',
            name='naxt_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Naxt hajmi [litr]'),
        ),
        migrations.AddField(
            model_name='salefuel',
            name='plastig_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Plastig hajmi [litr]'),
        ),
        migrations.AddIndex(
            model_name='salefuel',
            index=models.Index(fields=['fuel_type'], name='sale_fuel_fuel_ty_898f7f_idx'),
        ),
    ]
