# Generated by Django 4.2.10 on 2024-03-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_salefuel_sale_fuel_day_id_ca1d4d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salefuel',
            old_name='plastig_size',
            new_name='card_size',
        ),
        migrations.RenameField(
            model_name='salefuel',
            old_name='naxt_size',
            new_name='cash_size',
        ),
    ]
