# Generated by Django 5.0.1 on 2024-02-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tashkilot qisqacha nomi')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('leader', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rahbar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Xolat to'liq nomi")),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xolat qisqacha nomi')),
            ],
            options={
                'verbose_name': 'Xolat',
                'verbose_name_plural': 'Xolatlar',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'lov turi [to'liq nomi]")),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'lov turi [qisqa nomi]")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Xolat')),
            ],
            options={
                'verbose_name': "To'lov turi",
                'verbose_name_plural': "To'lov turlari",
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Yoqilg'i turi [to'liq nomi]")),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name="Yoqilg'i turi [qisqa nomi]")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Xolat')),
            ],
            options={
                'verbose_name': "Yoqilg'i turi",
                'verbose_name_plural': "Yoqilg'i turlari",
                'db_table': 'fuel_type',
            },
        ),
    ]
