# Generated by Django 5.0.1 on 2024-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='attr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa nomi'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='title',
            field=models.CharField(max_length=255, verbose_name="To'liq nomi"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='attr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa nomi'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=255, verbose_name="To'liq nomi"),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='attr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa nomi'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='title',
            field=models.CharField(max_length=255, verbose_name="To'liq nomi"),
        ),
        migrations.AlterField(
            model_name='state',
            name='attr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='qisqacha nomi'),
        ),
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(max_length=255, verbose_name="to'liq nomi"),
        ),
    ]
