# Generated by Django 5.0.1 on 2024-02-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_fuel_fuelcolumn_fuelcolumnpointer_fuelprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Foydalanuvchi nomi')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana")),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Xolat')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'user',
            },
        ),
    ]
