# Generated by Django 5.0.1 on 2024-02-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_admin_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='state',
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Xolat')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi turi',
                'verbose_name_plural': 'Foydalanuvchi turlari',
                'db_table': 'user_types',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.usertypes', verbose_name='Foydalanuvchi turi'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
