# Generated by Django 5.0.1 on 2024-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(related_name='user_organization', to='bot.organization', verbose_name='Tashkilotlar'),
        ),
    ]
