# Generated by Django 5.0.1 on 2024-02-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozimi'),
        ),
    ]
