# Generated by Django 5.0.1 on 2024-02-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_salefuel_price_alter_salefuel_size'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salefuel',
            new_name='sale_fuel_day_id_ca1d4d_idx',
            old_name='sale_fuel_day_a5ac4b_idx',
        ),
        migrations.AlterField(
            model_name='salefuel',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.fuel', verbose_name='Kun'),
        ),
    ]
